// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbLoginResponse userspb login response
//
// swagger:model userspbLoginResponse
type UserspbLoginResponse struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this userspb login response
func (m *UserspbLoginResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb login response based on context it is used
func (m *UserspbLoginResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbLoginResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbLoginResponse) UnmarshalBinary(b []byte) error {
	var res UserspbLoginResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
