// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbRegisterUserRequest userspb register user request
//
// swagger:model userspbRegisterUserRequest
type UserspbRegisterUserRequest struct {

	// name
	Name string `json:"name,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`
}

// Validate validates this userspb register user request
func (m *UserspbRegisterUserRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb register user request based on context it is used
func (m *UserspbRegisterUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbRegisterUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbRegisterUserRequest) UnmarshalBinary(b []byte) error {
	var res UserspbRegisterUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
