// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserspbRegisterUserResponse userspb register user response
//
// swagger:model userspbRegisterUserResponse
type UserspbRegisterUserResponse struct {

	// id
	ID string `json:"id,omitempty"`
}

// Validate validates this userspb register user response
func (m *UserspbRegisterUserResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this userspb register user response based on context it is used
func (m *UserspbRegisterUserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserspbRegisterUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserspbRegisterUserResponse) UnmarshalBinary(b []byte) error {
	var res UserspbRegisterUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
