// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CentrifugoProxyRefreshRequest centrifugo proxy refresh request
//
// swagger:model CentrifugoProxyRefreshRequest
type CentrifugoProxyRefreshRequest struct {

	// client
	Client string `json:"client,omitempty"`

	// encoding
	Encoding string `json:"encoding,omitempty"`

	// meta
	// Format: byte
	Meta strfmt.Base64 `json:"meta,omitempty"`

	// protocol
	Protocol string `json:"protocol,omitempty"`

	// transport
	Transport string `json:"transport,omitempty"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this centrifugo proxy refresh request
func (m *CentrifugoProxyRefreshRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this centrifugo proxy refresh request based on context it is used
func (m *CentrifugoProxyRefreshRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CentrifugoProxyRefreshRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CentrifugoProxyRefreshRequest) UnmarshalBinary(b []byte) error {
	var res CentrifugoProxyRefreshRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
