// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CentrifugoProxyChannelsCapability centrifugo proxy channels capability
//
// swagger:model CentrifugoProxyChannelsCapability
type CentrifugoProxyChannelsCapability struct {

	// allow
	Allow []string `json:"allow"`

	// channels
	Channels []string `json:"channels"`

	// match
	Match string `json:"match,omitempty"`
}

// Validate validates this centrifugo proxy channels capability
func (m *CentrifugoProxyChannelsCapability) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this centrifugo proxy channels capability based on context it is used
func (m *CentrifugoProxyChannelsCapability) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CentrifugoProxyChannelsCapability) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CentrifugoProxyChannelsCapability) UnmarshalBinary(b []byte) error {
	var res CentrifugoProxyChannelsCapability
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
