// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CentrifugoProxyConnectRequest centrifugo proxy connect request
//
// swagger:model CentrifugoProxyConnectRequest
type CentrifugoProxyConnectRequest struct {

	// b64data
	B64data string `json:"b64data,omitempty"`

	// channels
	Channels []string `json:"channels"`

	// client
	Client string `json:"client,omitempty"`

	// data
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`

	// encoding
	Encoding string `json:"encoding,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// protocol
	Protocol string `json:"protocol,omitempty"`

	// transport
	Transport string `json:"transport,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this centrifugo proxy connect request
func (m *CentrifugoProxyConnectRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this centrifugo proxy connect request based on context it is used
func (m *CentrifugoProxyConnectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CentrifugoProxyConnectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CentrifugoProxyConnectRequest) UnmarshalBinary(b []byte) error {
	var res CentrifugoProxyConnectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
