// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CentrifugoProxySubRefreshRequest centrifugo proxy sub refresh request
//
// swagger:model CentrifugoProxySubRefreshRequest
type CentrifugoProxySubRefreshRequest struct {

	// channel
	Channel string `json:"channel,omitempty"`

	// client
	Client string `json:"client,omitempty"`

	// encoding
	Encoding string `json:"encoding,omitempty"`

	// meta
	// Format: byte
	Meta strfmt.Base64 `json:"meta,omitempty"`

	// protocol
	Protocol string `json:"protocol,omitempty"`

	// transport
	Transport string `json:"transport,omitempty"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this centrifugo proxy sub refresh request
func (m *CentrifugoProxySubRefreshRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this centrifugo proxy sub refresh request based on context it is used
func (m *CentrifugoProxySubRefreshRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CentrifugoProxySubRefreshRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CentrifugoProxySubRefreshRequest) UnmarshalBinary(b []byte) error {
	var res CentrifugoProxySubRefreshRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
