// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CentrifugoProxyBoolValue centrifugo proxy bool value
//
// swagger:model CentrifugoProxyBoolValue
type CentrifugoProxyBoolValue struct {

	// value
	Value bool `json:"value,omitempty"`
}

// Validate validates this centrifugo proxy bool value
func (m *CentrifugoProxyBoolValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this centrifugo proxy bool value based on context it is used
func (m *CentrifugoProxyBoolValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CentrifugoProxyBoolValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CentrifugoProxyBoolValue) UnmarshalBinary(b []byte) error {
	var res CentrifugoProxyBoolValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
