// Code generated by go-swagger; DO NOT EDIT.

package emulation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/emulation/emulationclient/models"
)

// StartReader is a Reader for the Start structure.
type StartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStartOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewStartDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewStartOK creates a StartOK with default headers values
func NewStartOK() *StartOK {
	return &StartOK{}
}

/*
StartOK describes a response with status code 200, with default header values.

A successful response.
*/
type StartOK struct {
	Payload models.EmulationpbStartEmulationResponse
}

// IsSuccess returns true when this start o k response has a 2xx status code
func (o *StartOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this start o k response has a 3xx status code
func (o *StartOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this start o k response has a 4xx status code
func (o *StartOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this start o k response has a 5xx status code
func (o *StartOK) IsServerError() bool {
	return false
}

// IsCode returns true when this start o k response a status code equal to that given
func (o *StartOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the start o k response
func (o *StartOK) Code() int {
	return 200
}

func (o *StartOK) Error() string {
	return fmt.Sprintf("[POST /api/emulation/start][%d] startOK  %+v", 200, o.Payload)
}

func (o *StartOK) String() string {
	return fmt.Sprintf("[POST /api/emulation/start][%d] startOK  %+v", 200, o.Payload)
}

func (o *StartOK) GetPayload() models.EmulationpbStartEmulationResponse {
	return o.Payload
}

func (o *StartOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStartDefault creates a StartDefault with default headers values
func NewStartDefault(code int) *StartDefault {
	return &StartDefault{
		_statusCode: code,
	}
}

/*
StartDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type StartDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this start default response has a 2xx status code
func (o *StartDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this start default response has a 3xx status code
func (o *StartDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this start default response has a 4xx status code
func (o *StartDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this start default response has a 5xx status code
func (o *StartDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this start default response a status code equal to that given
func (o *StartDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the start default response
func (o *StartDefault) Code() int {
	return o._statusCode
}

func (o *StartDefault) Error() string {
	return fmt.Sprintf("[POST /api/emulation/start][%d] start default  %+v", o._statusCode, o.Payload)
}

func (o *StartDefault) String() string {
	return fmt.Sprintf("[POST /api/emulation/start][%d] start default  %+v", o._statusCode, o.Payload)
}

func (o *StartDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *StartDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
