// Code generated by go-swagger; DO NOT EDIT.

package proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/proxy/proxyclient/models"
)

// ConnectReader is a Reader for the Connect structure.
type ConnectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConnectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConnectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewConnectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewConnectOK creates a ConnectOK with default headers values
func NewConnectOK() *ConnectOK {
	return &ConnectOK{}
}

/*
ConnectOK describes a response with status code 200, with default header values.

A successful response.
*/
type ConnectOK struct {
	Payload *models.CentrifugoProxyConnectResponse
}

// IsSuccess returns true when this connect o k response has a 2xx status code
func (o *ConnectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this connect o k response has a 3xx status code
func (o *ConnectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this connect o k response has a 4xx status code
func (o *ConnectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this connect o k response has a 5xx status code
func (o *ConnectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this connect o k response a status code equal to that given
func (o *ConnectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the connect o k response
func (o *ConnectOK) Code() int {
	return 200
}

func (o *ConnectOK) Error() string {
	return fmt.Sprintf("[POST /api/proxy/connect][%d] connectOK  %+v", 200, o.Payload)
}

func (o *ConnectOK) String() string {
	return fmt.Sprintf("[POST /api/proxy/connect][%d] connectOK  %+v", 200, o.Payload)
}

func (o *ConnectOK) GetPayload() *models.CentrifugoProxyConnectResponse {
	return o.Payload
}

func (o *ConnectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CentrifugoProxyConnectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConnectDefault creates a ConnectDefault with default headers values
func NewConnectDefault(code int) *ConnectDefault {
	return &ConnectDefault{
		_statusCode: code,
	}
}

/*
ConnectDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ConnectDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this connect default response has a 2xx status code
func (o *ConnectDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this connect default response has a 3xx status code
func (o *ConnectDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this connect default response has a 4xx status code
func (o *ConnectDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this connect default response has a 5xx status code
func (o *ConnectDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this connect default response a status code equal to that given
func (o *ConnectDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the connect default response
func (o *ConnectDefault) Code() int {
	return o._statusCode
}

func (o *ConnectDefault) Error() string {
	return fmt.Sprintf("[POST /api/proxy/connect][%d] connect default  %+v", o._statusCode, o.Payload)
}

func (o *ConnectDefault) String() string {
	return fmt.Sprintf("[POST /api/proxy/connect][%d] connect default  %+v", o._statusCode, o.Payload)
}

func (o *ConnectDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ConnectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
