// Code generated by go-swagger; DO NOT EDIT.

package proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/proxy/proxyclient/models"
)

// NewPublishParams creates a new PublishParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublishParams() *PublishParams {
	return &PublishParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublishParamsWithTimeout creates a new PublishParams object
// with the ability to set a timeout on a request.
func NewPublishParamsWithTimeout(timeout time.Duration) *PublishParams {
	return &PublishParams{
		timeout: timeout,
	}
}

// NewPublishParamsWithContext creates a new PublishParams object
// with the ability to set a context for a request.
func NewPublishParamsWithContext(ctx context.Context) *PublishParams {
	return &PublishParams{
		Context: ctx,
	}
}

// NewPublishParamsWithHTTPClient creates a new PublishParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublishParamsWithHTTPClient(client *http.Client) *PublishParams {
	return &PublishParams{
		HTTPClient: client,
	}
}

/*
PublishParams contains all the parameters to send to the API endpoint

	for the publish operation.

	Typically these are written to a http.Request.
*/
type PublishParams struct {

	// Body.
	Body *models.CentrifugoProxyPublishRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the publish params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishParams) WithDefaults() *PublishParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the publish params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublishParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the publish params
func (o *PublishParams) WithTimeout(timeout time.Duration) *PublishParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the publish params
func (o *PublishParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the publish params
func (o *PublishParams) WithContext(ctx context.Context) *PublishParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the publish params
func (o *PublishParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the publish params
func (o *PublishParams) WithHTTPClient(client *http.Client) *PublishParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the publish params
func (o *PublishParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the publish params
func (o *PublishParams) WithBody(body *models.CentrifugoProxyPublishRequest) *PublishParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the publish params
func (o *PublishParams) SetBody(body *models.CentrifugoProxyPublishRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublishParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
