// Code generated by go-swagger; DO NOT EDIT.

package proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/proxy/proxyclient/models"
)

// NewRefreshParams creates a new RefreshParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRefreshParams() *RefreshParams {
	return &RefreshParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRefreshParamsWithTimeout creates a new RefreshParams object
// with the ability to set a timeout on a request.
func NewRefreshParamsWithTimeout(timeout time.Duration) *RefreshParams {
	return &RefreshParams{
		timeout: timeout,
	}
}

// NewRefreshParamsWithContext creates a new RefreshParams object
// with the ability to set a context for a request.
func NewRefreshParamsWithContext(ctx context.Context) *RefreshParams {
	return &RefreshParams{
		Context: ctx,
	}
}

// NewRefreshParamsWithHTTPClient creates a new RefreshParams object
// with the ability to set a custom HTTPClient for a request.
func NewRefreshParamsWithHTTPClient(client *http.Client) *RefreshParams {
	return &RefreshParams{
		HTTPClient: client,
	}
}

/*
RefreshParams contains all the parameters to send to the API endpoint

	for the refresh operation.

	Typically these are written to a http.Request.
*/
type RefreshParams struct {

	// Body.
	Body *models.CentrifugoProxyRefreshRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the refresh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshParams) WithDefaults() *RefreshParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the refresh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RefreshParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the refresh params
func (o *RefreshParams) WithTimeout(timeout time.Duration) *RefreshParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the refresh params
func (o *RefreshParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the refresh params
func (o *RefreshParams) WithContext(ctx context.Context) *RefreshParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the refresh params
func (o *RefreshParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the refresh params
func (o *RefreshParams) WithHTTPClient(client *http.Client) *RefreshParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the refresh params
func (o *RefreshParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the refresh params
func (o *RefreshParams) WithBody(body *models.CentrifugoProxyRefreshRequest) *RefreshParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the refresh params
func (o *RefreshParams) SetBody(body *models.CentrifugoProxyRefreshRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RefreshParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
