// Code generated by go-swagger; DO NOT EDIT.

package proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/proxy/proxyclient/models"
)

// RefreshReader is a Reader for the Refresh structure.
type RefreshReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RefreshReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRefreshOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRefreshDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRefreshOK creates a RefreshOK with default headers values
func NewRefreshOK() *RefreshOK {
	return &RefreshOK{}
}

/*
RefreshOK describes a response with status code 200, with default header values.

A successful response.
*/
type RefreshOK struct {
	Payload *models.CentrifugoProxyRefreshResponse
}

// IsSuccess returns true when this refresh o k response has a 2xx status code
func (o *RefreshOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this refresh o k response has a 3xx status code
func (o *RefreshOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this refresh o k response has a 4xx status code
func (o *RefreshOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this refresh o k response has a 5xx status code
func (o *RefreshOK) IsServerError() bool {
	return false
}

// IsCode returns true when this refresh o k response a status code equal to that given
func (o *RefreshOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the refresh o k response
func (o *RefreshOK) Code() int {
	return 200
}

func (o *RefreshOK) Error() string {
	return fmt.Sprintf("[POST /api/proxy/refresh][%d] refreshOK  %+v", 200, o.Payload)
}

func (o *RefreshOK) String() string {
	return fmt.Sprintf("[POST /api/proxy/refresh][%d] refreshOK  %+v", 200, o.Payload)
}

func (o *RefreshOK) GetPayload() *models.CentrifugoProxyRefreshResponse {
	return o.Payload
}

func (o *RefreshOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CentrifugoProxyRefreshResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRefreshDefault creates a RefreshDefault with default headers values
func NewRefreshDefault(code int) *RefreshDefault {
	return &RefreshDefault{
		_statusCode: code,
	}
}

/*
RefreshDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RefreshDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this refresh default response has a 2xx status code
func (o *RefreshDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this refresh default response has a 3xx status code
func (o *RefreshDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this refresh default response has a 4xx status code
func (o *RefreshDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this refresh default response has a 5xx status code
func (o *RefreshDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this refresh default response a status code equal to that given
func (o *RefreshDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the refresh default response
func (o *RefreshDefault) Code() int {
	return o._statusCode
}

func (o *RefreshDefault) Error() string {
	return fmt.Sprintf("[POST /api/proxy/refresh][%d] refresh default  %+v", o._statusCode, o.Payload)
}

func (o *RefreshDefault) String() string {
	return fmt.Sprintf("[POST /api/proxy/refresh][%d] refresh default  %+v", o._statusCode, o.Payload)
}

func (o *RefreshDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RefreshDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
