// Code generated by go-swagger; DO NOT EDIT.

package proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/proxy/proxyclient/models"
)

// NewSubRefreshParams creates a new SubRefreshParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSubRefreshParams() *SubRefreshParams {
	return &SubRefreshParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSubRefreshParamsWithTimeout creates a new SubRefreshParams object
// with the ability to set a timeout on a request.
func NewSubRefreshParamsWithTimeout(timeout time.Duration) *SubRefreshParams {
	return &SubRefreshParams{
		timeout: timeout,
	}
}

// NewSubRefreshParamsWithContext creates a new SubRefreshParams object
// with the ability to set a context for a request.
func NewSubRefreshParamsWithContext(ctx context.Context) *SubRefreshParams {
	return &SubRefreshParams{
		Context: ctx,
	}
}

// NewSubRefreshParamsWithHTTPClient creates a new SubRefreshParams object
// with the ability to set a custom HTTPClient for a request.
func NewSubRefreshParamsWithHTTPClient(client *http.Client) *SubRefreshParams {
	return &SubRefreshParams{
		HTTPClient: client,
	}
}

/*
SubRefreshParams contains all the parameters to send to the API endpoint

	for the sub refresh operation.

	Typically these are written to a http.Request.
*/
type SubRefreshParams struct {

	// Body.
	Body *models.CentrifugoProxySubRefreshRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the sub refresh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubRefreshParams) WithDefaults() *SubRefreshParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the sub refresh params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SubRefreshParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the sub refresh params
func (o *SubRefreshParams) WithTimeout(timeout time.Duration) *SubRefreshParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sub refresh params
func (o *SubRefreshParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sub refresh params
func (o *SubRefreshParams) WithContext(ctx context.Context) *SubRefreshParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sub refresh params
func (o *SubRefreshParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sub refresh params
func (o *SubRefreshParams) WithHTTPClient(client *http.Client) *SubRefreshParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sub refresh params
func (o *SubRefreshParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the sub refresh params
func (o *SubRefreshParams) WithBody(body *models.CentrifugoProxySubRefreshRequest) *SubRefreshParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the sub refresh params
func (o *SubRefreshParams) SetBody(body *models.CentrifugoProxySubRefreshRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SubRefreshParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
