// Code generated by go-swagger; DO NOT EDIT.

package proxy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/proxy/proxyclient/models"
)

// SubscribeReader is a Reader for the Subscribe structure.
type SubscribeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubscribeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSubscribeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSubscribeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSubscribeOK creates a SubscribeOK with default headers values
func NewSubscribeOK() *SubscribeOK {
	return &SubscribeOK{}
}

/*
SubscribeOK describes a response with status code 200, with default header values.

A successful response.
*/
type SubscribeOK struct {
	Payload *models.CentrifugoProxySubscribeResponse
}

// IsSuccess returns true when this subscribe o k response has a 2xx status code
func (o *SubscribeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this subscribe o k response has a 3xx status code
func (o *SubscribeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this subscribe o k response has a 4xx status code
func (o *SubscribeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this subscribe o k response has a 5xx status code
func (o *SubscribeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this subscribe o k response a status code equal to that given
func (o *SubscribeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the subscribe o k response
func (o *SubscribeOK) Code() int {
	return 200
}

func (o *SubscribeOK) Error() string {
	return fmt.Sprintf("[POST /api/proxy/subscribe][%d] subscribeOK  %+v", 200, o.Payload)
}

func (o *SubscribeOK) String() string {
	return fmt.Sprintf("[POST /api/proxy/subscribe][%d] subscribeOK  %+v", 200, o.Payload)
}

func (o *SubscribeOK) GetPayload() *models.CentrifugoProxySubscribeResponse {
	return o.Payload
}

func (o *SubscribeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CentrifugoProxySubscribeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSubscribeDefault creates a SubscribeDefault with default headers values
func NewSubscribeDefault(code int) *SubscribeDefault {
	return &SubscribeDefault{
		_statusCode: code,
	}
}

/*
SubscribeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SubscribeDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this subscribe default response has a 2xx status code
func (o *SubscribeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this subscribe default response has a 3xx status code
func (o *SubscribeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this subscribe default response has a 4xx status code
func (o *SubscribeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this subscribe default response has a 5xx status code
func (o *SubscribeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this subscribe default response a status code equal to that given
func (o *SubscribeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the subscribe default response
func (o *SubscribeDefault) Code() int {
	return o._statusCode
}

func (o *SubscribeDefault) Error() string {
	return fmt.Sprintf("[POST /api/proxy/subscribe][%d] subscribe default  %+v", o._statusCode, o.Payload)
}

func (o *SubscribeDefault) String() string {
	return fmt.Sprintf("[POST /api/proxy/subscribe][%d] subscribe default  %+v", o._statusCode, o.Payload)
}

func (o *SubscribeDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SubscribeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
