// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Ahmed-Sermani/driver-tracking-system/users/usersclient/models"
)

// RegisterUserReader is a Reader for the RegisterUser structure.
type RegisterUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRegisterUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRegisterUserDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRegisterUserOK creates a RegisterUserOK with default headers values
func NewRegisterUserOK() *RegisterUserOK {
	return &RegisterUserOK{}
}

/*
RegisterUserOK describes a response with status code 200, with default header values.

A successful response.
*/
type RegisterUserOK struct {
	Payload *models.UserspbRegisterUserResponse
}

// IsSuccess returns true when this register user o k response has a 2xx status code
func (o *RegisterUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this register user o k response has a 3xx status code
func (o *RegisterUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this register user o k response has a 4xx status code
func (o *RegisterUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this register user o k response has a 5xx status code
func (o *RegisterUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this register user o k response a status code equal to that given
func (o *RegisterUserOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the register user o k response
func (o *RegisterUserOK) Code() int {
	return 200
}

func (o *RegisterUserOK) Error() string {
	return fmt.Sprintf("[POST /api/users][%d] registerUserOK  %+v", 200, o.Payload)
}

func (o *RegisterUserOK) String() string {
	return fmt.Sprintf("[POST /api/users][%d] registerUserOK  %+v", 200, o.Payload)
}

func (o *RegisterUserOK) GetPayload() *models.UserspbRegisterUserResponse {
	return o.Payload
}

func (o *RegisterUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UserspbRegisterUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRegisterUserDefault creates a RegisterUserDefault with default headers values
func NewRegisterUserDefault(code int) *RegisterUserDefault {
	return &RegisterUserDefault{
		_statusCode: code,
	}
}

/*
RegisterUserDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type RegisterUserDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this register user default response has a 2xx status code
func (o *RegisterUserDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this register user default response has a 3xx status code
func (o *RegisterUserDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this register user default response has a 4xx status code
func (o *RegisterUserDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this register user default response has a 5xx status code
func (o *RegisterUserDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this register user default response a status code equal to that given
func (o *RegisterUserDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the register user default response
func (o *RegisterUserDefault) Code() int {
	return o._statusCode
}

func (o *RegisterUserDefault) Error() string {
	return fmt.Sprintf("[POST /api/users][%d] registerUser default  %+v", o._statusCode, o.Payload)
}

func (o *RegisterUserDefault) String() string {
	return fmt.Sprintf("[POST /api/users][%d] registerUser default  %+v", o._statusCode, o.Payload)
}

func (o *RegisterUserDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *RegisterUserDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
