---
applicationName: "application"

deployment:
  enabled: true
  replicas: 2
  strategy:
    type: RollingUpdate

  env:
    ENVIRONMENT:
      value: production

    PG_CONN:
      value: "postgres://app-user:your-password@postgres-postgresql.db/drivertrackingsystem"

    JWT_SECRET:
      value: "jwt_secret"

    CENT_CONN:
      value: "http://centrifugo.messaging:9000/api"

    CENT_KEY:
      value: "api_key"
  image:
    repository: docker.io/library/monolith
    tag: "latest"
    pullPolicy: IfNotPresent

  readinessProbe:
    enabled: true
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    initialDelaySeconds: 10
    httpGet:
      path: /healthz
      port: 8080

  resources:
    limits:
      memory: 64Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 100m

  containerSecurityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: false

  ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8085
      name: grpc
      protocol: TCP

service:
  enabled: true

  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 8085
      name: grpc
      protocol: TCP
      targetPort: 8085
  type: ClusterIP

ingress:
  enabled: true

  ingressClassName: "nginx"

  servicePort: http

  hosts:
    - host: ""
      paths:
        - path: /app(/|$)(.*)
          pathType: Prefix

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
