---
auth:
  username: app-user
  password: your-password
  database: "drivertrackingsystem"

replication:
  enabled: true
  readReplicas: 1
  synchronousCommit: "on"
  numSynchronousReplicas: 1

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    scrapeTimeout: 10s

primary:
  persistence:
    enabled: true
    storageClass: standard
    size: 3Gi

readReplicas:
  persistence:
    enabled: true
    storageClass: standard
    size: 3Gi
