---
architecture: replication

auth:
  enabled: true
  password: your-password

master:
  count: 1

  persistence:
    enabled: true
    size: "100Mi"
    accessModes:
      - ReadWriteOnce

  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    size: "100Mi"
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

metrics:
  enabled: true
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

  serviceMonitor:
    enabled: true
    namespace: monitoring
